### ISSUE TITLE
Extension is unable run test with same in same file scope with describe

### ISSUE THREAD

**Issue by eratio08** [zxch3n/vitest-explorer#2]
The extension will fail with
```
Test result not found. 

Can you run vitest successfully on this file? Does it need custom option to run?

Does this file contain test case with the same name? 
```

if the following setup is present:
```typescript
describe('example', () => {
    describe('scope 1', () => {
        test('potential same name', () => {
         ...
        });
    })
    describe('scope 2', () => {
        test('potential same name', () => {
         ...
        });
    })
})
```

It this a deliberate choice?

**Comment by zxch3n** [comment]
Yeah, because the current vitest output files don't have enough information to differentiate the test cases with the same names. Maybe this can be fixed in the future when this plugin switches to use vitest server. I'll make a patch to let the plugin try to resolve the tests - which will probably go wrong when testing the async functions - while raising warnings.

**Comment by zxch3n** [comment]
Oh, I found that Jest test results include the information I need to deduce the concrete test cases. That format makes more sense. Since vitest is obeying jest interfaces to maximize compatibility, I'll make a PR to vitest.
